### ISSUE TITLE
Accessibility tests with cypress-axe

### ISSUE THREAD

**Issue by dmanners** [elgentos/magento2-cypress-testing-suite#110]
We have been using cypress-axe https://github.com/component-driven/cypress-axe in our projects to not only test our system's functionality but also levels of accessibility. The test themselves are not so complex, most of the timte it's visit page and run the a11y test. We have also extended the logging to show more detailed information in our pipeline such as which elements are causing the issues and a detailed description.

Our current setup is a different test suite for accessibility as our normal test suite so that we can run them against different instances.

We would be more than happy to contribute this back to the repo if it would be interesting to have as part of the repository. Happy to discuss options and further ideas around accessibility checks.

**Comment by peterjaap** [comment]
Wow that's an amazing resource. I'd totally love to have this incorporated in this project! But maybe make it optional to make sure it's backward compatible?

**Comment by dmanners** [comment]
@peterjaap cool. We will have to clear a few things here internally with regards to how we can open source contributions but once that is sorted out we would be happy to contribute.
