### ISSUE TITLE
Update to Cypress 13

### ISSUE THREAD

**Issue by norgeindian** [elgentos/magento2-cypress-testing-suite#116]
Would it be possible to update to Cypress version 13?
If so, what steps would be required to do that? Will be happy to do as much as I can, if someone tells me a bit, what to take care of.

**Comment by sprankhub** [comment]
Having a look at https://github.com/elgentos/magento2-cypress-testing-suite/commit/63b91d940a61eb32f65999ce9b196b9f3947e05f, there might not be too much to do :joy:
