### ISSUE TITLE
Add cypress-tags support

### ISSUE THREAD

**Issue by peterjaap** [elgentos/magento2-cypress-testing-suite#20]
closes #26 
[Tagging](https://github.com/annaet/cypress-tags) of write tests (hot vs readonly ) CYPRESS_INCLUDE_TAGS=hot npx cypress run , if you run npx cypress run it should only run the non-hot tests

If we are going to add tag support the tech notes need to be added to the allround readme

## Definition of done

- [x] Check all specs on potential hot tests
- [x] Add a script alias that runs only non hot tests
- [x] Add a stript alias that includes hot tests

## Tech notes

Install tag support (uses typescript): `npm install cypress-tags typescript --save-dev`

Running the tests with tags:
- Excluding 'hot' tests: `npm run cypress`
- Only 'hot' tests: `npm run cypress-hot`

**Comment by AndrewRMillar** [comment]
Completed by #26
