### ISSUE TITLE
Support mobile tests

### ISSUE THREAD

**Issue by phoenix-bjoern** [elgentos/magento2-cypress-testing-suite#25]
Cypress can run tests based on viewports (see Cypress real world example: https://github.com/cypress-io/cypress-realworld-app/blob/develop/.gitlab-ci.yml). This also makes a lot of sense for eCommerce sites with responsive design.
Consider to add test cases based on different viewports.

**Comment by peterjaap** [comment]
There's been work done on this for the Luma tests, but not for the Hyva tests yet.

**Comment by vladhorielov** [comment]
@peterjaap Could you check your Hyva tests again as you have errors and the tests can't complete successfully? After the fix, I can continue with the implementation of mobile tests for the Hyva theme

Tests with problems: 
1. cart.spec.js
2. minicart.spec.js
3. spec.js
4. spec.js
5. spec.js

**Comment by peterjaap** [comment]
:partying_face: !
