### ISSUE TITLE
Add github actions to run the tests on a plain magento

### ISSUE THREAD

**Issue by amenk** [elgentos/magento2-cypress-testing-suite#51]
We (@kolaente) would like to have / add a GitHub action which run the cypress tests on GitHub

Possible starting points:

https://github.com/extdn/github-actions-m2 -> but I am not sure if that runs a Magento instance which can be accessed by Cypress 

This is how Shopware does Cypress tests: https://github.com/shopware/platform/blob/trunk/.github/workflows/03-e2e.yml

**Comment by sprankhub** [comment]
Maybe also check out https://github.com/graycoreio/github-actions-magento2 :)

**Comment by amenk** [comment]
Very interesting, thanks.

PS: I will not have time in the near future to work on this issue here - anyone who wants to take over is very welcome :-) I tried some things [here](https://github.com/amenk/magento2-cypress-testing-suite/tree/51-github-action) but it was more or less a failure and I feel I took the wrong approach.

**Comment by peterjaap** [comment]
Done!

**Comment by peterjaap** [comment]
https://github.com/elgentos/magento2-cypress-testing-suite/blob/main/.github/workflows/main.yml

https://github.com/elgentos/magento2-cypress-testing-suite/actions/runs/3053615539/jobs/4924464391
