### ISSUE TITLE
Cypress version 10.0.0 no longer supports cypress.json.

### ISSUE THREAD

**Issue by BorisovskiP** [elgentos/magento2-cypress-testing-suite#52]
**Describe the bug**
Using `"cypress": "^10.0"` will throw the following error: `Cypress version 10.0.0 no longer supports cypress.json.`

**To Reproduce**
Steps to reproduce the behaviour:
1. Require `"cypress": "^10.0"`
2. Run `npx cypress run --spec ./cypress/integration/path/to/some.spec.js`

**Expected behaviour**
Using the current version of cypress should work with the module

**Additional context**
A current workaround to this is to have a dependency on `"cypress": "^9.7.0`

**Comment by Vinai** [comment]
I think the proper solution is to replace the `cypress.json` with a file `cypress.config.js`:

```js
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  "baseUrl": "https://example.com/",
  "watchForFileChanges": false,
  "viewportWidth": 1920,
  "viewportHeight": 1080,
  "env": {
    "mobileViewportWidthBreakpoint": 768,
    "mobileViewportWidthBreakpointHyva": 1024
  }
});
```

Reference https://docs.cypress.io/guides/references/migration-guide#Configuration-File-Changes
