### ISSUE TITLE
Create pipeline for new PR

### ISSUE THREAD

**Issue by phoenix-bjoern** [elgentos/magento2-cypress-testing-suite#63]
For each new PR the changes have to be verified manually. It would be handy for run a Github Actions pipeline which executes the Cypress tests. At least for Hyvä can be used as an endpoint http://demo.hyva.io/.

**Comment by Vinai** [comment]
At least the tests that do not require admin credentials or a user account besides Veronica Costello can be run...

**Comment by peterjaap** [comment]
Done!

**Comment by peterjaap** [comment]
https://github.com/elgentos/magento2-cypress-testing-suite/blob/main/.github/workflows/main.yml

https://github.com/elgentos/magento2-cypress-testing-suite/actions/runs/3053615539/jobs/4924464391
