### ISSUE TITLE
Cypress AWS Codepileline Issue

### ISSUE THREAD

**Issue by sankharay** [elgentos/magento2-cypress-testing-suite#64]
**Describe the bug**
when I run cypress with record Id I am getting an error that " wrong project id " but instead of the project id system showing me my record key as project id.. screenshot attached.

https://ibb.co/hVWGz8P

**Comment by sankharay** [comment]
https://ibb.co/hVWGz8P

**Comment by sankharay** [comment]
[https://ibb.co/hVWGz8P](url)

**Comment by Vinai** [comment]
I don't think the issue is related to the magento2-cypress-testing-suite.

**Comment by peterjaap** [comment]
Agreed with Vinai
