### ISSUE TITLE
Sensless default spec pattern 

### ISSUE THREAD

**Issue by Vinai** [elgentos/magento2-cypress-testing-suite#65]
The default spec pattern is set to `cypress/integration/**/*.spec.js` (see [MR](https://github.com/elgentos/magento2-cypress-testing-suite/pull/61/files#r951612373)).

This doesn't make any sense, since it will work neither with Luma nor with Hyvä.
The default value should be more useful.

**Expected behavior**
Ideally the matching integration tests are executed automatically, maybe by running a preflight check in `cypress.config.js` against the `baseUrl` and determining the theme.

**Comment by peterjaap** [comment]
I'm curious as to how you use this package then. Your test suite should contain either Hyvä tests *or* Luma tests, not both. When I start implementing this, I copy over the whole suite and then remove the tests I don't need, so in that case the pattern is correct.

**Comment by Vinai** [comment]
We run the tests on a stock Hyvä theme, so we don't need to modify the tests at all.
I basically clone the repo, set the target URL in a variable, and run the tests.

**Comment by Vinai** [comment]
The nice thing about the preflight check is it will enable the use of the unmodified testsuite against demo stores.

**Comment by peterjaap** [comment]
Ok I guess your situation is the odd one out since you're basically the only one that doesn't modify the store it runs against ;)

But there's no harm in adding the preflight check
