### ISSUE TITLE
Pull request #85 breaks test suite

### ISSUE THREAD

**Issue by Vinai** [elgentos/magento2-cypress-testing-suite#87]
**Describe the bug**

After merging https://github.com/elgentos/magento2-cypress-testing-suite/pull/85 a number of tests stopped passing.
Reproduced on Magento 2.4.4 and 2.4.5 with sample data and Hyvä Theme 1.1.17.

More specifically:
```
Category page tests
    1) Can visit the category page and filters on color red

Perform searches
    1) Can find a single product
    2) Can see suggestions when entering search terms

**Comment by peterjaap** [comment]
Looks like the tests are all passing now? https://github.com/elgentos/magento2-cypress-testing-suite/actions/runs/3191777864

**Comment by peterjaap** [comment]
Triggered one manually now https://github.com/elgentos/magento2-cypress-testing-suite/actions/runs/3195223915

**Comment by peterjaap** [comment]
See #93
